[package]
edition = "2021"
name = "cve_analyzer"
version = "0.1.0"

[dependencies]
prost = "0.11"
reqwest = "0.11"
rusqlite = "0.28"
serde = {version = "1.0"}
serde_json = "1.0"
tokio = {version = "1.21", features = ["full"]}
zip = "0.6"

[build-dependencies]
prost-build = "0.11"
